### ISSUE TITLE
Complex vectors

### ISSUE THREAD

**Issue by mayakwd** [jonnyreeves/as3-vanilla#4] opened 2013-05-08 05:51 UTC
Hello! 
Vanilla can't parse complex vectors like:

``` actionscript3
var data : Object = JSON.decode('{"value": [[1,2,3],[2,3,4],[3,4,5]]}');
var cards : Cards = extract(data, Cards);

public class Cards {
  public var value : Vector.<Vector.<uint>>;
}
```

The vectors are created, but are filled with incorrect values

**Comment by jonnyreeves** [comment] 2013-05-19 12:19
Thanks for the report, just got back from holiday :)  

I see you have fixed this bug with tests in your fork, would you like to raise a pull request for that and I can get it merged back in?

Thanks!

**Comment by jonnyreeves** [comment] 2013-05-20 10:41
Duplicate of #5

**Closed as completed by jonnyreeves** 2013-05-20 10:41 UTC
